extends Node

@warning_ignore_start("unused_signal")
signal restart_scene()
signal change_scene(new_scene_path : String)
signal change_bgm(audio_stream : AudioStream, crossfade_duration : float)
signal spawn_vfx(vfx_key : String, vfx_transform : Transform3D)
signal spawn_vfx_attached(vfx_key : String, parent : Node3D)
signal camera_changed(new_camera : Camera3D)
signal shake_all_cameras(shake_info : ShakeInfo)
signal plr_input_state_changed(new_state : bool)
signal plr_hud_state_changed(new_state : bool)
signal plr_chr_changed(new_chr : CombatCharacter)
signal plr_show_tutorial_action(tutorial_action : TutorialActionDisplay)
signal new_area_reached(new_area_name : String)
signal boss_health_changed(new_health : int, max_health : int)
signal boss_spawned(boss_name : String, boss_start_health : int, boss_max_health : int)
signal boss_died()

@warning_ignore_restore("unused_signal")
